import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import { ThemeProvider } from '@/layout/components/theme-provider'

import './globals.css'

import { Navbar } from '@/layout/components/navbar'
import { NavigationSidebar } from '@/layout/components/navigation-sidebar'
import { ThemeToggle } from '@/layout/components/theme-toggle'
import { SidebarInset, SidebarProvider } from '@/shared/components/sidebar'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute='class' defaultTheme='dark' disableTransitionOnChange enableSystem>
          <SidebarProvider>
            <NavigationSidebar />
            <SidebarInset>
              <Navbar />
              <ThemeToggle />
              {children}
            </SidebarInset>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
